export default {
open_module (butt) {	
if (butt==='N'){
									 showModal(KeyPerson.name)
									 p_pincode_ins.setDisabled(false)
									 p_state_ins.setDisabled(false)
									 p_district_ins.setDisabled(false)
									 p_taluk_ins.setDisabled(false)
									 p_post_ins.setDisabled(false)
									 p_Locality_ins.setDisabled(false)
									 p_street_ins.setDisabled(false)
									 p_doorNo_ins.setDisabled(false)
									 p_addressLine1_ins.setDisabled(false)
									 p_addressLine2_ins.setDisabled(false)
									 p_gpsCoardinates_ins.setDisabled(false)
									 partner_name_ins.setDisabled(false)
									 partner_fathers_name_ins.setDisabled(false)
									 partner_phone_ins.setDisabled(false)
									 partner_email_ins.setDisabled(false)
									 partner_dateOfBirth_ins.setDisabled(false)
									 partner_aadhar_number_ins.setDisabled(false)
									 Aadhar.setDisabled(false)
									 partner_pan_ins.setDisabled(false)
									 PAN.setDisabled(false)
									 partner_sharing_ratio_ins.setDisabled(false)
									 partner_capitalContribution_in.setDisabled(false)
									 partner_designation_ins.setDisabled(false)
									 partner_bank_auth_ins.setDisabled(false)
									 Address_Doc.setDisabled(false)
									 photo.setImage('')
									 partner_name_ins.setValue('')
									 partner_fathers_name_ins.setValue('')
									 partner_email_ins.setValue('')
									 partner_dateOfBirth_ins.setValue('')
									 partner_aadhar_number_ins.setValue('')
									 partner_pan_ins.setValue('')
									 partner_sharing_ratio_ins.setValue('')
									 partner_capitalContribution_in.setValue('')
									 partner_designation_ins.setSelectedOption('')
									 partner_bank_auth_ins.setValue('')	
									 KeyPerId.setValue(0)
									 Address_Doc.setDisabled(false)
								   Button45.setDisabled(false)             	
									 Button46.setDisabled(false)
									 resetWidget('PAN')
									 resetWidget('Aadhaar')
									 resetWidget('kp_photo')
									 resetWidget('Address_Doc')		
}
else if (butt='V'){
								   showModal(KeyPerson.name)
								   photo.setVisibility(true)
									 partner_name_ins.setValue(key_person.selectedRow.name)
									 partner_fathers_name_ins.setValue(key_person.selectedRow.father_name)
									 partner_email_ins.setValue(key_person.selectedRow.email)
                   partner_dateOfBirth_ins.setValue(key_person.selectedRow.dob)
									 partner_aadhar_number_ins.setValue(key_person.selectedRow.aadhar)
									 Aadhar.setDisabled(key_person.selectedRow.aadhar)
									 partner_pan_ins.setValue(key_person.selectedRow.pan)
									 PAN.setDisabled(key_person.selectedRow.pan)
									 partner_sharing_ratio_ins.setValue(key_person.selectedRow.sharing_ratio)
									 partner_capitalContribution_in.setValue(key_person.selectedRow.capital_contribution)
									 partner_designation_ins.setSelectedOption(key_person.selectedRow.desiganation)
									 partner_bank_auth_ins.setValue(key_person.selectedRow.bank_authorization)
	                 p_pincode_ins.setValue(key_person.selectedRow.pincode)
					     		 p_state_ins.setSelectedOption(key_person.selectedRow.State)
                   p_district_ins.setSelectedOption(key_person.selectedRow.District)
	                 p_taluk_ins.setSelectedOption(key_person.selectedRow["Taluk City"])
	                 p_post_ins.setSelectedOption(key_person.selectedRow.Post)
									 p_Locality_ins.setSelectedOption(key_person.selectedRow["Area Locality"])
									 p_street_ins.setValue(key_person.selectedRow.Street)
									 p_doorNo_ins.setValue(key_person.selectedRow["Door No"])
		      				 p_addressLine1_ins.setValue(key_person.selectedRow["Address Line 1"])
								 	 p_addressLine2_ins.setValue(key_person.selectedRow["Address Line 2"])	
		               p_gpsCoardinates_ins.setValue(key_person.selectedRow["GPS Coordinates"])
		               kp_photo.setVisibility(true)
									 partner_name_ins.setDisabled(true)
									 partner_fathers_name_ins.setDisabled(true)
									 partner_phone_ins.setDisabled(true)
									 partner_email_ins.setDisabled(true)
									 partner_dateOfBirth_ins.setDisabled(true)
									 partner_aadhar_number_ins.setDisabled(true)
									 Aadhar.setDisabled(false)
									 partner_pan_ins.setDisabled(true)
									 PAN.setDisabled(false)
									 partner_sharing_ratio_ins.setDisabled(true)
									 partner_capitalContribution_in.setDisabled(true)
									 partner_designation_ins.setDisabled(true)
									 partner_bank_auth_ins.setDisabled(true)
									 p_pincode_ins.setDisabled(true)
									 p_state_ins.setDisabled(true)
									 p_district_ins.setDisabled(true)
									 p_taluk_ins.setDisabled(true)
									 p_post_ins.setDisabled(true)
									 p_Locality_ins.setDisabled(true)
									 p_street_ins.setDisabled(true)
									 p_doorNo_ins.setDisabled(true)
									 p_addressLine1_ins.setDisabled(true)
									 p_addressLine2_ins.setDisabled(true)
									 p_gpsCoardinates_ins.setDisabled(true)
									 Address_Doc.setDisabled(true)
								   Button45.setDisabled(true)             	
									 Button46.setDisabled(true)
}
else if (butt==='E'){
		              showModal(KeyPerson.name)
									photo.setVisibility(true)
		              partner_name_ins.setDisabled(false)
		              partner_fathers_name_ins.isDisabled(false)
									partner_phone_ins.setDisabled(false)
									partner_email_ins.setDisabled(false)
		              partner_dateOfBirth_ins.setDisabled(false)
									 partner_aadhar_number_ins.setDisabled(false)
									 Aadhar.setDisabled(false)
									 partner_pan_ins.setDisabled(false)
									 PAN.setDisabled(false)
									 partner_sharing_ratio_ins.setDisabled(false)
									 partner_capitalContribution_in.setDisabled(false)
									 partner_designation_ins.setDisabled(false)
									 partner_bank_auth_ins.setDisabled(false)
									 KeyPerId.setValue(0)
									 p_pincode_ins.setDisabled(false)
									 p_state_ins.setDisabled(false)
									 p_district_ins.setDisabled(false)
									 p_taluk_ins.setDisabled(false)
									 p_post_ins.setDisabled(false)
									 p_Locality_ins.setDisabled(false)
									 p_street_ins.setDisabled(false)
									 p_doorNo_ins.setDisabled(false)
									 p_addressLine1_ins.setDisabled(false)
									 p_addressLine2_ins.setDisabled(false)
									 p_gpsCoardinates_ins.setDisabled(false)
									 Address_Doc.setDisabled(false)
									 KeyPerId.setValue(0)
									 Address_Doc.setDisabled(false)
								   Button45.setDisabled(false)             	
									 Button46.setDisabled(false)
		               partner_name_ins.setValue(key_person.selectedRow.name)
									 partner_fathers_name_ins.setValue(key_person.selectedRow.father_name)
									 partner_dateOfBirth_ins.setValue(key_person.selectedRow.dob)
		               partner_aadhar_number_ins.setValue(key_person.selectedRow.aadhar)
									 Aadhar.setDisabled(key_person.selectedRow.aadhar)
		               partner_pan_ins.setValue(key_person.selectedRow.pan)
									 PAN.setDisabled(key_person.selectedRow.pan)
									 partner_sharing_ratio_ins.setValue(key_person.selectedRow.sharing_ratio)
									 partner_capitalContribution_in.setValue(key_person.selectedRow.capital_contribution)
									 partner_designation_ins.setSelectedOption(key_person.selectedRow.desiganation)
									 partner_bank_auth_ins.setValue(key_person.selectedRow.bank_authorization)
		               p_pincode_ins.setValue(key_person.selectedRow.pincode)
					     		 p_state_ins.setSelectedOption(key_person.selectedRow.State)
									 p_district_ins.setSelectedOption(key_person.selectedRow.District)
									 p_taluk_ins.setSelectedOption(key_person.selectedRow["Taluk City"])
									 p_post_ins.setSelectedOption(key_person.selectedRow.Post)
									 p_Locality_ins.setSelectedOption(key_person.selectedRow["Area Locality"])
									 p_street_ins.setValue(key_person.selectedRow.Street)
									 p_doorNo_ins.setValue(key_person.selectedRow["Door No"])
		      				 p_addressLine1_ins.setValue(key_person.selectedRow["Address Line 1"])
								 	 p_addressLine2_ins.setValue(key_person.selectedRow["Address Line 2"])	
		               p_gpsCoardinates_ins.setValue(key_person.selectedRow["GPS Coordinates"])
		               KeyPerId.setValue(key_person.selectedRow.key_per_id)         
	}
},
async key_per_mgt () {
		if(KeyPerId.text==0){
								await KeyPerIns.run()
								KeyPerId.setValue(KeyPerIns.data.data.KeyPerIns.returning[0].key_per_id)
				if(KeyPerIns.data.data.KeyPerIns.returning[0].key_per_id>0){
										
        }
    } 
}	
	
}




										
																																															 